version: "3.9"

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./volumes/qdrant:/qdrant/storage
    restart: always # Restart policy
    networks:
      - qdrant_network

  app:
    container_name: interactive_storytelling_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: always # Restart policy
    networks:
      - qdrant_network

networks:
  qdrant_network:
    driver: bridge
